# AI

In [2]:
# Liberaires to be imported
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np # import functions or call functions
import os
import nltk
import requests # work with urls
from bs4 import BeautifulSoup # base python librayr for web scraping
import re

In [3]:
retailweb = requests.get("https://www.ibef.org/industry/retail-india")

In [4]:
retailweb

In [5]:
retailtxt = BeautifulSoup(retailweb.text)

In [6]:
retailtxt = retailtxt.getText(strip = True)

In [7]:
retailtxt

'Retail Industry in India: Overview of Retail Sector, Market Size, Growth...IBEFLOGINHomeAbout usAnnual ReportsBoard of TrusteesCareersTendersIndian EconomyDomestic InvestmentsEconomic Survey 2025-26Export Promotion MissionForeign Direct InvestmentForeign Institutional InvestorsForeign Trade Policy 2023Government SchemesIndia PositiveIndia-UK FTAIndia: A SnapshotIndian Economy NewsIndian Economy OverviewIndian Investments AbroadInvestmentsMake in IndiaMonthly Economic ReportPolicy WatchQuarterly NewsletterQuick FactsStartup IndiaTradeUnion Budget 2025-26Union Budget 2026-27Useful LinksIndustryAgriculture and Allied IndustriesAuto ComponentsAutomobilesAviationAyushBankingBiotechnologyCementChemicalsConsumer DurablesDefence ManufacturingE-CommerceEducation and TrainingElectric VehicleElectronics System Design & ManufacturingEngineering and Capital GoodsFinancial ServicesFMCGFood ProcessingGems and JewelleryHealthcareInfrastructureInsuranceIT & BPMManufacturingMedia and EntertainmentMedical DevicesMetals and MiningMSMEOil and GasPaper & PackagingPharmaceuticalsPortsPowerRailwaysReal EstateRenewable EnergyRetailRoadsScience and TechnologyServicesSteelTelecommunicationsTextilesTourism and HospitalityStates/UTAndaman and NicobarAndhra PradeshArunachal PradeshAssamBiharChandigarhChhattisgarhDadra & Nagar Haveli and Daman & DiuDelhiGoaGujaratHaryanaHimachal PradeshJammu and KashmirJharkhandKarnatakaKeralaLadakhLakshadweepMadhya PradeshMaharashtraManipurMeghalayaMizoramNagalandOdishaPuducherryPunjabRajasthanSikkimTamil NaduTelanganaTripuraUttar PradeshUttarakhandWest BengalExportsExport By ProductsExport By CountryAgriculture and FoodApparelCarpetsCashewChemicalsCoconutCoffeeCoirCottonElectronic and Computer SoftwareEngineeringGems and JewelleryHandicraftsHandloomJuteLeatherMarine ProductsOilseedsPharmaceuticalPlasticsPowerloomServicesShellac and Forest ProductsSilkSpicesSportsSynthetic and Rayon TextilesTeaTobaccoWoolWool and WoollenAustraliaBangladeshBelgiumCanadaChinaFranceGermanyHong KongIndonesiaIsraelItalyJapanKoreaMalaysiaNetherlandsRussiaSaudi ArabiaSingaporeSouth AfricaThailandTurkeyUAEUKUSVietnamBlogContactMoreResearchCase StudiesEXIM ProcedureMedia & EventsEventsFilmsImage GalleryMedia CoveragePostersOther LinksTendersArchiveCampaignsDiscover IndiaBasmati RiceIndian MilletsOrganic ProductsIndian FruitsIndian TeaBharat Mobility 2025GI of IndiaExperience IndiaRetail Industry in IndiaIndia’s e-commerce sector is expected to reach US$ 53.08 billion in 2024, with an annual growth rate of 11.45% to reach  US$ 91.24 billion by 2029.Explore Other IndustriesAgriculture and Allied IndustriesAuto ComponentsAutomobilesAviationAyushBankingBiotechnologyCementChemicalsConsumer DurablesDefence ManufacturingE-CommerceEducation and TrainingElectric VehicleElectronics System Design & ManufacturingEngineering and Capital GoodsFinancial ServicesFMCGFood ProcessingGems and JewelleryHealthcareInfrastructureInsuranceIT & BPMManufacturingMedia and EntertainmentMedical DevicesMetals and MiningMSMEOil and GasPaper & PackagingPharmaceuticalsPortsPowerRailwaysReal EstateRenewable EnergyRetailRoadsScience and TechnologyServicesSteelTelecommunicationsTextilesTourism and HospitalityAdvantage IndiaRobustDemand*Reliance Industries, India’s largest retailer, stated that the country is set to emerge as the world’s third-largest retail market by 2030, supported by government initiatives aimed at enhancing disposable incomes and driving consumption.*India’s retail sector leasing reached over 4 million square feet in Q4 2025, driving total retail leasing to a record ~8.9 million square feet in 2025 across the top seven cities. Delhi-NCR led the leasing with new mall constructions, facilitating new store openings in key micro markets. D2C brands are expanding their physical presence in fashion, apparel, jewellery, cosmetics, and wellness categories.*As of FY25, India’s has the third highest number of e-retail shoppers globally.InnovationIn Financing*Collective efforts of financial houses and banks with retailers are enabling consumers to go for durable products with easy credit.*India’s consumer and retail sector recorded 146 deals worth US$ 1.5 billion in Q1 2026, with deal volume rising 21% sequentially and deal value declining 55%, reflecting a shift toward smaller, strategic transactions. The quarter was led by domestic consolidation and outbound activity, while personal care and textiles, apparel & accessories together accounted for 39% of total deals by volume.IncreasingInvestments*Due to India’s wealth of resources, availability of labor at relatively low costs, and special investment wages such tax breaks, etc., foreign corporations prefer to invest here.*India’s retail trading sector attracted Rs. 36,241.37 crore (US$ 4.97 billion) FDIs between April 2000-December 2025.*In January 2026, IKEA announced plans to invest over Rs. 20,000 crore (US$ 2.2 billion) in India over the next five years to expand its retail network, strengthen logistics infrastructure and increase local sourcing as part of its long-term growth strategy in the Indian retail market.PolicySupport*To improve the business climate and make it simpler for foreign companies to register fully owned subsidiaries in India, the Indian government has implemented a number of rules, regulations, and policies.SnapshotShowcaseInfographicsReportsRelated NewsLast updated: Feb, 2026Retail Industry ReportFeb, 2026IntroductionThe Indian retail industry has emerged as one of the most dynamic and fast-paced sectors, driven by strong consumer demand and the entry of new players. Contributing over 10% to the country’s GDP and around 8% to employment, India is today the world’s third-largest retail market and ranked 63 in the World Bank’s Doing Business 2023 report. With its vast middle class and largely untapped potential, India continues to attract global retail giants seeking to enter high-growth markets.Rising purchasing power, especially among urban consumers, is reshaping spending patterns. Branded goods across categories such as apparel, cosmetics, footwear, watches, beverages, food, and jewellery are increasingly becoming part of everyday consumption and lifestyle. India’s retail sector is on track to exceed US$ 2361.11 billion by 2030 from US$ 1093.89 billion in 2025, with organised retail expected to capture more than 35% of the total market.The sector’s growth is further reinforced by expanding retail infrastructure. India’s seven largest cities alone are expected to add 16.6 million sq. ft. of new shopping mall space by 2026, according to Anarock.Organised retail in India is projected to reach US$ 230 billion by 2030, driven by rising disposable incomes, increasing urbanisation and evolving consumer preferences, according to a Deloitte–RAI report.India today ranks among the most attractive destinations for retail investment, supported by its demographic advantage, the world’s largest population, a growing middle-income segment of ~158 million households, increasing urbanisation, connected rural consumers, and rising household spending. The government has also introduced progressive policies and reforms to improve the business climate, making it easier for foreign players to establish wholly owned subsidiaries and tap into India’s retail potential.India’s retail sector leasing reached over 4 million square feet in Q4 2025, driving total retail leasing to a record ~8.9 million square feet in 2025 across the top seven cities. Delhi-NCR led the leasing with new mall constructions, facilitating new store openings in key micro markets. D2C brands are expanding their physical presence in fashion, apparel, jewellery, cosmetics, and wellness categories.Market SizeIndia’s direct selling industry was valued at Rs. 22,022 crore (US$ 2.57 billion) in FY24, reflecting the resilience of the country’s consumption story despite global challenges. By FY25, India had become the world’s third-largest e-retail market by shopper base, behind only China and the US. The rapid expansion of new-age logistics is expected to further boost this growth, with an estimated 2.5 billion Direct-to-Consumer (D2C) shipments projected by 2030.India’s e-commerce market was valued at US$ 129.72 billion in 2025 and is projected to reach US$ 651.10 billion by 2034, supported by rising internet penetration, digital payments, and growing consumer preference for online shopping. Reliance Industries, India’s largest retailer, has highlighted that the country is poised to emerge as the world’s third-largest retail market by 2030, with government initiatives aimed at boosting disposable incomes and driving consumption. The e-commerce ecosystem is also witnessing parallel growth in infrastructure. The India e-commerce warehousing market size reached US$ 10.0 billion in 2025, and expected to reach US$ 39.1 billion by 2034, exhibiting a growth rate (CAGR) of 16.42% during 2026-34. India’s broader digital economy is projected to touch Rs. 68,55,200 crore (US$ 800 billion) by 2030, up from Rs. 34,44,738 crore (US$ 402 billion) in 2023, while employing nearly 14.67 million workers.Investments/ DevelopmentsThe Retail sector in India has seen a lot of investments and developments in the recent past.India\'s fastest consumer growth is coming from Tier-II and Tier-III cities, which are adding nearly 100 million new consumers to branded and organised retail by 2030. The rise of these cities is driving national consumption patterns, digital payments, and the expansion of D2C brands with faster trial and repeat purchases.\u200bIndia’s retail sector leasing reached over 4 million square feet in Q4 2025, driving total retail leasing to a record ~8.9 million square feet in 2025 across the top seven cities. Delhi-NCR led the leasing with new mall constructions, facilitating new store openings in key micro markets. D2C brands are expanding their physical presence in fashion, apparel, jewellery, cosmetics, and wellness categories.India’s retail sector continued to witness strong expansion in 2026, with retailers opening new stores across multiple formats and categories, supported by rising investments, expanding mall supply and growing consumer demand across major cities.India\'s retail market is poised to reach US$ 1 trillion by 2030. This growth is driven by rising incomes, faster digital adoption, and the rise of an aspirational consumer class. New retail formats like e-commerce, quick commerce, and D2C brands are scaling faster than conventional companies, indicating a structural shift in shopping habits and huge investor interest.In January 2026, IKEA announced plans to invest over Rs. 20,000 crore (US$ 2.2 billion) in India over the next five years to expand its retail network, strengthen logistics infrastructure and increase local sourcing as part of its long-term growth strategy in the Indian retail market.India’s luxury retail market continued to witness strong growth in Q4 2025, with overall retail leasing reaching a record ~8.9 million sq. ft., driven by rising demand from premium and luxury brands across major cities. The growth was supported by experience-led flagship stores, premium retail formats and increasing affluent consumer spending.Retailers are expanding their private label offerings to meet this demand. For instance, Reliance Retail is intensifying its focus on private labels in the consumer durables sector, aiming to challenge established global brands.A report by EY indicates that 52% of Indian consumers are opting for private label products in 2025, with 70% acknowledging that these brands are increasingly offering better quality products.AstorMueller AG has entered India’s retail market through a joint venture with Gaurik Group called Nuvora, aiming to launch 10 to 12 exclusive Bugatti stores across the top 20 cities in FY26.According to Bain & Company’s 2026 e-retail report, India’s online retail market is witnessing a gradual shift from cash-on-delivery (COD) to digital payment modes such as UPI-based payments at delivery, reflecting rising adoption of digital transactions across online shopping platforms.In January 2026, Xiaomi said 100% of its phones and TVs sold in India are manufactured locally, while wearables and tablets are also made in India; local sourcing has risen to about 35% of its components.In November 2025, Lush re-entered India through a licensing partnership with Bilberry Brands, starting online and planning physical stores in key cities such as New Delhi, Mumbai and Bengaluru.In December 2025, Prada announced a limited-edition “Made in India” Kolhapuri-inspired sandal collection, set to launch in February 2026 across 40 global stores and online, in collaboration with Indian artisan bodies.In December 2025, lululemon announced plans to expand into six new international markets in 2026, including India through a partnership with Tata CLiQ, with the brand set to launch through Tata CLiQ Luxury and Tata CLiQ Fashion platforms alongside its first physical store in the country.In FY25, Zudio more than doubled its store count, from approximately 341 to 765 outlets across 235 cities, driving its milestone of over Rs. 8,569 crore (US$ 1 billion) in revenue.In 2025, over 30 global brands entered India, underscoring the country’s growing appeal for international retailers and premium consumer brands.In February 2026, Nykaa opened 11 new stores and entered four new cities in Q3 FY26, taking its total store count to 276.In January 2026, Tim Hortons India opened two new outlets at Navi Mumbai International Airport, strengthening its presence across high-footfall transit locations.In January 2026, IKEA said it will invest over Rs. 20,000 crores (US$ 2.2 billion) in India over the next five years to expand its retail network, logistics and local sourcing.In November 2025, LuLu Group revived its Visakhapatnam mall project after signing a fresh MoU with the Andhra Pradesh government, with the project expected to create new direct and indirect jobs.As of November 2025, Reliance Retail operates 20,000 stores across with a retail area of over 77.4 million sq. ft. in India.In February 2026, India’s CPI inflation stood at 3.21% (provisional), with rural inflation at 3.37% and urban inflation at 3.02%, while food inflation was 3.47%.India’s retail trading sector attracted Rs. 36,241.37 crore (US$ 4.97 billion) FDIs between April 2000-December 2025.India’s consumer and retail sector recorded 146 deals worth US$ 1.5 billion in Q1 2026, with deal volume rising 21% sequentially and deal value declining 55%, reflecting a shift toward smaller, strategic transactions. The quarter was led by domestic consolidation and outbound activity, while personal care and textiles, apparel & accessories together accounted for 39% of total deals by volume.By 2030, India’s per capita income is expected to exceed Rs. 3,49,000 (US$ 4,000) from Rs 2,34,859 (US$ 2,740) in FY25, unlocking new business opportunities across sectors. Expanding digital commerce, growing access to credit, and fintech-driven financial inclusion further accelerate this consumption boom.India\'s Rs. 1,71,860 crore (US$ 20 billion) cosmetics and beauty market are poised to benefit from the India-UK free trade agreement (FTA), which will reduce duties on cosmetics and other products. The FTA will directly benefit retailers like Nykaa, Reliance Tira, and Shoppers Stop, as well as e-commerce platforms like Amazon and Myntra, which sell premium beauty products.India’s private final consumption expenditure (PFCE) is estimated at Rs. 2,19,63,865 crore (US$ 2485.30 billion) in FY26 (First Advance Estimates), growing 8.2% over the previous year and accounting for 61.5% of GDP. As per Economic Survey 2025-26 PFCE will grew 7.0% in FY26, supported by low inflation, stable employment and rising real purchasing power.India\'s seven major cities are set to receive 16.6 million square feet (sq. ft.) of prime retail space in new shopping malls by the end of 2026, as per Anarock\'s data.In February 2026, Hindustan Unilever approved the acquisition of the remaining 49% stake in Zywie Ventures (OZiva) for Rs. 824 crore (US$ 93.24 million) and the divestment of its 19.8% stake in Nutritionalab for Rs. 307 crore (US$ 34.74 million), strengthening its health and wellbeing portfolio.In February 2026, Reliance Consumer Products acquired 100% equity stake in Southern Health Foods Private Limited, maker of the Manna brand, for Rs. 156.42 crore (US$ 17.70 million), adding to its health foods and staples portfolio.French sports retailer Decathlon is accelerating its investments to ramp up production and enhance its retail presence further in India.In February 2026, Trent said it had added over 100 stores in the nine months to December 2025, taking its total store count to more than 1,100 and accelerating expansion in smaller towns and suburban markets.Reliance Industries is likely to sell another 8-10% stake in Reliance Retail Ventures Ltd (RRVL) to fund expansion, retire debt and prepare for the initial public offering of the conglomerate\'s retail business.Reliance Consumer Products, the FMCG arm of Reliance Retail announced the launch of it made-for-India consumer packaged goods brand \'Independence\' in Gujarat.Retail tech companies supporting the retail sector with services such as digital ledgers, inventory management, payments solutions, and tools for logistics and fulfilment are taking off in India.With the rising need for consumer goods in different sectors including consumer electronics and home appliances, many companies have invested in the Indian retail space in the past few months.Growth Drivers for retail in IndiaGold loans are driving India’s retail credit growth, rising 35% YoY to Rs. 1,06,00,000 crore (US$ 1.23 trillion) in FY25, boosted by higher gold values and easier credit from public sector banks and NBFCs.From FY20 to FY25, digital transactions have surged, exceeding 65,000 crore in number and totalling more than Rs. 1,20,00,00,000 crore (US$ 140 trillion).As of February 2026, UPI transactions reached 20.39 billion worth Rs. 26.84 lakh crore (US$ 303.69 billion), registering a 27% year-on-year growth in transaction volume and a 22% increase in transaction value, reflecting rapid growth in digital payment adoption across retail merchant outlets.Favourable Demographics: India’s large and young population, Rising Middle Class, Urbanization, Changing Lifestyle and Consumption Patterns and favourable government initiatives prove to be a growth engine for the retail industry.Change in consumer mindset: The transition from traditional retail to online platforms in India has spurred a shift in consumer mindset. This change is characterized by a prioritization of convenience, a wider product selection, increased price sensitivity, growing trust in online transactions, reliance on reviews and recommendations, evolving loyalty dynamics, a greater embrace of technology, and heightened expectations for fast delivery. A new CBRE & Invest India survey has revealed a significant shift in India\'s retail landscape, driven by a growing consumer demand for experience-based entertainment. Over 70% of respondents across various age groups prefer participatory activities such as bowling, amusement parks, rock climbing, escape rooms, and children\'s play zones over passive options like museums or art exhibitions. Mini-sized beauty products are gaining traction in India, driven by affordability, convenience, and the desire for experimentation, particularly among Gen Z. These small packs, often called "minis," are reshaping the Indian beauty market as more consumers look to experiment with makeup at the "right" price.Brand consciousness: Brand consciousness in India is a multifaceted phenomenon shaped by economic, cultural, and technological factors. As consumer expectations continue to evolve, brands must remain agile and responsive to changing trends, ensuring that they deliver value, innovation, and authe

In [8]:
# Text PreProcessing - remove punctuations, digit, special char, stopwords
# Regular Expression are speficic string aptterns for cleaning text
#d+ for digits, D+ for non digits, w+ for words are some examples

In [9]:
retailtxt = re.sub(r'[^a-zA-Z0-9\s.]','',retailtxt)
# pattern to replace, pattenrn replacement, data

In [10]:
retailtxt

'Retail Industry in India Overview of Retail Sector Market Size Growth...IBEFLOGINHomeAbout usAnnual ReportsBoard of TrusteesCareersTendersIndian EconomyDomestic InvestmentsEconomic Survey 202526Export Promotion MissionForeign Direct InvestmentForeign Institutional InvestorsForeign Trade Policy 2023Government SchemesIndia PositiveIndiaUK FTAIndia A SnapshotIndian Economy NewsIndian Economy OverviewIndian Investments AbroadInvestmentsMake in IndiaMonthly Economic ReportPolicy WatchQuarterly NewsletterQuick FactsStartup IndiaTradeUnion Budget 202526Union Budget 202627Useful LinksIndustryAgriculture and Allied IndustriesAuto ComponentsAutomobilesAviationAyushBankingBiotechnologyCementChemicalsConsumer DurablesDefence ManufacturingECommerceEducation and TrainingElectric VehicleElectronics System Design  ManufacturingEngineering and Capital GoodsFinancial ServicesFMCGFood ProcessingGems and JewelleryHealthcareInfrastructureInsuranceIT  BPMManufacturingMedia and EntertainmentMedical DevicesMetals and MiningMSMEOil and GasPaper  PackagingPharmaceuticalsPortsPowerRailwaysReal EstateRenewable EnergyRetailRoadsScience and TechnologyServicesSteelTelecommunicationsTextilesTourism and HospitalityStatesUTAndaman and NicobarAndhra PradeshArunachal PradeshAssamBiharChandigarhChhattisgarhDadra  Nagar Haveli and Daman  DiuDelhiGoaGujaratHaryanaHimachal PradeshJammu and KashmirJharkhandKarnatakaKeralaLadakhLakshadweepMadhya PradeshMaharashtraManipurMeghalayaMizoramNagalandOdishaPuducherryPunjabRajasthanSikkimTamil NaduTelanganaTripuraUttar PradeshUttarakhandWest BengalExportsExport By ProductsExport By CountryAgriculture and FoodApparelCarpetsCashewChemicalsCoconutCoffeeCoirCottonElectronic and Computer SoftwareEngineeringGems and JewelleryHandicraftsHandloomJuteLeatherMarine ProductsOilseedsPharmaceuticalPlasticsPowerloomServicesShellac and Forest ProductsSilkSpicesSportsSynthetic and Rayon TextilesTeaTobaccoWoolWool and WoollenAustraliaBangladeshBelgiumCanadaChinaFranceGermanyHong KongIndonesiaIsraelItalyJapanKoreaMalaysiaNetherlandsRussiaSaudi ArabiaSingaporeSouth AfricaThailandTurkeyUAEUKUSVietnamBlogContactMoreResearchCase StudiesEXIM ProcedureMedia  EventsEventsFilmsImage GalleryMedia CoveragePostersOther LinksTendersArchiveCampaignsDiscover IndiaBasmati RiceIndian MilletsOrganic ProductsIndian FruitsIndian TeaBharat Mobility 2025GI of IndiaExperience IndiaRetail Industry in IndiaIndias ecommerce sector is expected to reach US 53.08 billion in 2024 with an annual growth rate of 11.45 to reach  US 91.24 billion by 2029.Explore Other IndustriesAgriculture and Allied IndustriesAuto ComponentsAutomobilesAviationAyushBankingBiotechnologyCementChemicalsConsumer DurablesDefence ManufacturingECommerceEducation and TrainingElectric VehicleElectronics System Design  ManufacturingEngineering and Capital GoodsFinancial ServicesFMCGFood ProcessingGems and JewelleryHealthcareInfrastructureInsuranceIT  BPMManufacturingMedia and EntertainmentMedical DevicesMetals and MiningMSMEOil and GasPaper  PackagingPharmaceuticalsPortsPowerRailwaysReal EstateRenewable EnergyRetailRoadsScience and TechnologyServicesSteelTelecommunicationsTextilesTourism and HospitalityAdvantage IndiaRobustDemandReliance Industries Indias largest retailer stated that the country is set to emerge as the worlds thirdlargest retail market by 2030 supported by government initiatives aimed at enhancing disposable incomes and driving consumption.Indias retail sector leasing reached over 4 million square feet in Q4 2025 driving total retail leasing to a record 8.9 million square feet in 2025 across the top seven cities. DelhiNCR led the leasing with new mall constructions facilitating new store openings in key micro markets. D2C brands are expanding their physical presence in fashion apparel jewellery cosmetics and wellness categories.As of FY25 Indias has the third highest number of eretail shoppers globally.InnovationIn FinancingCollective efforts of financial houses and banks with retailers are enabling consumers to go for durable products with easy credit.Indias consumer and retail sector recorded 146 deals worth US 1.5 billion in Q1 2026 with deal volume rising 21 sequentially and deal value declining 55 reflecting a shift toward smaller strategic transactions. The quarter was led by domestic consolidation and outbound activity while personal care and textiles apparel  accessories together accounted for 39 of total deals by volume.IncreasingInvestmentsDue to Indias wealth of resources availability of labor at relatively low costs and special investment wages such tax breaks etc. foreign corporations prefer to invest here.Indias retail trading sector attracted Rs. 36241.37 crore US 4.97 billion FDIs between April 2000December 2025.In January 2026 IKEA announced plans to invest over Rs. 20000 crore US 2.2 billion in India over the next five years to expand its retail network strengthen logistics infrastructure and increase local sourcing as part of its longterm growth strategy in the Indian retail market.PolicySupportTo improve the business climate and make it simpler for foreign companies to register fully owned subsidiaries in India the Indian government has implemented a number of rules regulations and policies.SnapshotShowcaseInfographicsReportsRelated NewsLast updated Feb 2026Retail Industry ReportFeb 2026IntroductionThe Indian retail industry has emerged as one of the most dynamic and fastpaced sectors driven by strong consumer demand and the entry of new players. Contributing over 10 to the countrys GDP and around 8 to employment India is today the worlds thirdlargest retail market and ranked 63 in the World Banks Doing Business 2023 report. With its vast middle class and largely untapped potential India continues to attract global retail giants seeking to enter highgrowth markets.Rising purchasing power especially among urban consumers is reshaping spending patterns. Branded goods across categories such as apparel cosmetics footwear watches beverages food and jewellery are increasingly becoming part of everyday consumption and lifestyle. Indias retail sector is on track to exceed US 2361.11 billion by 2030 from US 1093.89 billion in 2025 with organised retail expected to capture more than 35 of the total market.The sectors growth is further reinforced by expanding retail infrastructure. Indias seven largest cities alone are expected to add 16.6 million sq. ft. of new shopping mall space by 2026 according to Anarock.Organised retail in India is projected to reach US 230 billion by 2030 driven by rising disposable incomes increasing urbanisation and evolving consumer preferences according to a DeloitteRAI report.India today ranks among the most attractive destinations for retail investment supported by its demographic advantage the worlds largest population a growing middleincome segment of 158 million households increasing urbanisation connected rural consumers and rising household spending. The government has also introduced progressive policies and reforms to improve the business climate making it easier for foreign players to establish wholly owned subsidiaries and tap into Indias retail potential.Indias retail sector leasing reached over 4 million square feet in Q4 2025 driving total retail leasing to a record 8.9 million square feet in 2025 across the top seven cities. DelhiNCR led the leasing with new mall constructions facilitating new store openings in key micro markets. D2C brands are expanding their physical presence in fashion apparel jewellery cosmetics and wellness categories.Market SizeIndias direct selling industry was valued at Rs. 22022 crore US 2.57 billion in FY24 reflecting the resilience of the countrys consumption story despite global challenges. By FY25 India had become the worlds thirdlargest eretail market by shopper base behind only China and the US. The rapid expansion of newage logistics is expected to further boost this growth with an estimated 2.5 billion DirecttoConsumer D2C shipments projected by 2030.Indias ecommerce market was valued at US 129.72 billion in 2025 and is projected to reach US 651.10 billion by 2034 supported by rising internet penetration digital payments and growing consumer preference for online shopping. Reliance Industries Indias largest retailer has highlighted that the country is poised to emerge as the worlds thirdlargest retail market by 2030 with government initiatives aimed at boosting disposable incomes and driving consumption. The ecommerce ecosystem is also witnessing parallel growth in infrastructure. The India ecommerce warehousing market size reached US 10.0 billion in 2025 and expected to reach US 39.1 billion by 2034 exhibiting a growth rate CAGR of 16.42 during 202634. Indias broader digital economy is projected to touch Rs. 6855200 crore US 800 billion by 2030 up from Rs. 3444738 crore US 402 billion in 2023 while employing nearly 14.67 million workers.Investments DevelopmentsThe Retail sector in India has seen a lot of investments and developments in the recent past.Indias fastest consumer growth is coming from TierII and TierIII cities which are adding nearly 100 million new consumers to branded and organised retail by 2030. The rise of these cities is driving national consumption patterns digital payments and the expansion of D2C brands with faster trial and repeat purchases.Indias retail sector leasing reached over 4 million square feet in Q4 2025 driving total retail leasing to a record 8.9 million square feet in 2025 across the top seven cities. DelhiNCR led the leasing with new mall constructions facilitating new store openings in key micro markets. D2C brands are expanding their physical presence in fashion apparel jewellery cosmetics and wellness categories.Indias retail sector continued to witness strong expansion in 2026 with retailers opening new stores across multiple formats and categories supported by rising investments expanding mall supply and growing consumer demand across major cities.Indias retail market is poised to reach US 1 trillion by 2030. This growth is driven by rising incomes faster digital adoption and the rise of an aspirational consumer class. New retail formats like ecommerce quick commerce and D2C brands are scaling faster than conventional companies indicating a structural shift in shopping habits and huge investor interest.In January 2026 IKEA announced plans to invest over Rs. 20000 crore US 2.2 billion in India over the next five years to expand its retail network strengthen logistics infrastructure and increase local sourcing as part of its longterm growth strategy in the Indian retail market.Indias luxury retail market continued to witness strong growth in Q4 2025 with overall retail leasing reaching a record 8.9 million sq. ft. driven by rising demand from premium and luxury brands across major cities. The growth was supported by experienceled flagship stores premium retail formats and increasing affluent consumer spending.Retailers are expanding their private label offerings to meet this demand. For instance Reliance Retail is intensifying its focus on private labels in the consumer durables sector aiming to challenge established global brands.A report by EY indicates that 52 of Indian consumers are opting for private label products in 2025 with 70 acknowledging that these brands are increasingly offering better quality products.AstorMueller AG has entered Indias retail market through a joint venture with Gaurik Group called Nuvora aiming to launch 10 to 12 exclusive Bugatti stores across the top 20 cities in FY26.According to Bain  Companys 2026 eretail report Indias online retail market is witnessing a gradual shift from cashondelivery COD to digital payment modes such as UPIbased payments at delivery reflecting rising adoption of digital transactions across online shopping platforms.In January 2026 Xiaomi said 100 of its phones and TVs sold in India are manufactured locally while wearables and tablets are also made in India local sourcing has risen to about 35 of its components.In November 2025 Lush reentered India through a licensing partnership with Bilberry Brands starting online and planning physical stores in key cities such as New Delhi Mumbai and Bengaluru.In December 2025 Prada announced a limitededition Made in India Kolhapuriinspired sandal collection set to launch in February 2026 across 40 global stores and online in collaboration with Indian artisan bodies.In December 2025 lululemon announced plans to expand into six new international markets in 2026 including India through a partnership with Tata CLiQ with the brand set to launch through Tata CLiQ Luxury and Tata CLiQ Fashion platforms alongside its first physical store in the country.In FY25 Zudio more than doubled its store count from approximately 341 to 765 outlets across 235 cities driving its milestone of over Rs. 8569 crore US 1 billion in revenue.In 2025 over 30 global brands entered India underscoring the countrys growing appeal for international retailers and premium consumer brands.In February 2026 Nykaa opened 11 new stores and entered four new cities in Q3 FY26 taking its total store count to 276.In January 2026 Tim Hortons India opened two new outlets at Navi Mumbai International Airport strengthening its presence across highfootfall transit locations.In January 2026 IKEA said it will invest over Rs. 20000 crores US 2.2 billion in India over the next five years to expand its retail network logistics and local sourcing.In November 2025 LuLu Group revived its Visakhapatnam mall project after signing a fresh MoU with the Andhra Pradesh government with the project expected to create new direct and indirect jobs.As of November 2025 Reliance Retail operates 20000 stores across with a retail area of over 77.4 million sq. ft. in India.In February 2026 Indias CPI inflation stood at 3.21 provisional with rural inflation at 3.37 and urban inflation at 3.02 while food inflation was 3.47.Indias retail trading sector attracted Rs. 36241.37 crore US 4.97 billion FDIs between April 2000December 2025.Indias consumer and retail sector recorded 146 deals worth US 1.5 billion in Q1 2026 with deal volume rising 21 sequentially and deal value declining 55 reflecting a shift toward smaller strategic transactions. The quarter was led by domestic consolidation and outbound activity while personal care and textiles apparel  accessories together accounted for 39 of total deals by volume.By 2030 Indias per capita income is expected to exceed Rs. 349000 US 4000 from Rs 234859 US 2740 in FY25 unlocking new business opportunities across sectors. Expanding digital commerce growing access to credit and fintechdriven financial inclusion further accelerate this consumption boom.Indias Rs. 171860 crore US 20 billion cosmetics and beauty market are poised to benefit from the IndiaUK free trade agreement FTA which will reduce duties on cosmetics and other products. The FTA will directly benefit retailers like Nykaa Reliance Tira and Shoppers Stop as well as ecommerce platforms like Amazon and Myntra which sell premium beauty products.Indias private final consumption expenditure PFCE is estimated at Rs. 21963865 crore US 2485.30 billion in FY26 First Advance Estimates growing 8.2 over the previous year and accounting for 61.5 of GDP. As per Economic Survey 202526 PFCE will grew 7.0 in FY26 supported by low inflation stable employment and rising real purchasing power.Indias seven major cities are set to receive 16.6 million square feet sq. ft. of prime retail space in new shopping malls by the end of 2026 as per Anarocks data.In February 2026 Hindustan Unilever approved the acquisition of the remaining 49 stake in Zywie Ventures OZiva for Rs. 824 crore US 93.24 million and the divestment of its 19.8 stake in Nutritionalab for Rs. 307 crore US 34.74 million strengthening its health and wellbeing portfolio.In February 2026 Reliance Consumer Products acquired 100 equity stake in Southern Health Foods Private Limited maker of the Manna brand for Rs. 156.42 crore US 17.70 million adding to its health foods and staples portfolio.French sports retailer Decathlon is accelerating its investments to ramp up production and enhance its retail presence further in India.In February 2026 Trent said it had added over 100 stores in the nine months to December 2025 taking its total store count to more than 1100 and accelerating expansion in smaller towns and suburban markets.Reliance Industries is likely to sell another 810 stake in Reliance Retail Ventures Ltd RRVL to fund expansion retire debt and prepare for the initial public offering of the conglomerates retail business.Reliance Consumer Products the FMCG arm of Reliance Retail announced the launch of it madeforIndia consumer packaged goods brand Independence in Gujarat.Retail tech companies supporting the retail sector with services such as digital ledgers inventory management payments solutions and tools for logistics and fulfilment are taking off in India.With the rising need for consumer goods in different sectors including consumer electronics and home appliances many companies have invested in the Indian retail space in the past few months.Growth Drivers for retail in IndiaGold loans are driving Indias retail credit growth rising 35 YoY to Rs. 10600000 crore US 1.23 trillion in FY25 boosted by higher gold values and easier credit from public sector banks and NBFCs.From FY20 to FY25 digital transactions have surged exceeding 65000 crore in number and totalling more than Rs. 1200000000 crore US 140 trillion.As of February 2026 UPI transactions reached 20.39 billion worth Rs. 26.84 lakh crore US 303.69 billion registering a 27 yearonyear growth in transaction volume and a 22 increase in transaction value reflecting rapid growth in digital payment adoption across retail merchant outlets.Favourable Demographics Indias large and young population Rising Middle Class Urbanization Changing Lifestyle and Consumption Patterns and favourable government initiatives prove to be a growth engine for the retail industry.Change in consumer mindset The transition from traditional retail to online platforms in India has spurred a shift in consumer mindset. This change is characterized by a prioritization of convenience a wider product selection increased price sensitivity growing trust in online transactions reliance on reviews and recommendations evolving loyalty dynamics a greater embrace of technology and heightened expectations for fast delivery. A new CBRE  Invest India survey has revealed a significant shift in Indias retail landscape driven by a growing consumer demand for experiencebased entertainment. Over 70 of respondents across various age groups prefer participatory activities such as bowling amusement parks rock climbing escape rooms and childrens play zones over passive options like museums or art exhibitions. Minisized beauty products are gaining traction in India driven by affordability convenience and the desire for experimentation particularly among Gen Z. These small packs often called minis are reshaping the Indian beauty market as more consumers look to experiment with makeup at the right price.Brand consciousness Brand consciousness in India is a multifaceted phenomenon shaped by economic cultural and technological factors. As consumer expectations continue to evolve brands must remain agile and responsive to changing trends ensuring that they deliver value innovation and authenticity to maintain their competitive edge in the market.Government InitiativesThe Government of India has taken various initiatives to improve the retail industry in India. Some of them are listed belowIn December 2025 the Government of India said the seven PM MITRA Parks are expected to attract nearly Rs. 70000 crore US 7.92 billion in investments and generate around 10 lakh employment opportunities aimed at strengthening integrated retail and textile manufacturing ecosystems across multiple states

In [11]:
retailtxt = re.sub(r'[0-9]+','',retailtxt)

In [12]:
retailtxt = re.sub(r'Rs.','',retailtxt)

In [13]:
retailtxt

'Retail Industry in India Overview of Retail Sector Market Size Growth...IBEFLOGINHomeAbout usAnnual ReportsBoard of TrusteesCareersTendersIndian EconomyDomestic InvestmentsEconomic Survey Export Promotion MissionForeign Direct InvestmentForeign Institutional InvestorsForeign Trade Policy Government SchemesIndia PositiveIndiaUK FTAIndia A SnapshotIndian Economy NewsIndian Economy OverviewIndian Investments AbroadInvestmentsMake in IndiaMonthly Economic ReportPolicy WatchQuarterly NewsletterQuick FactsStartup IndiaTradeUnion Budget Union Budget Useful LinksIndustryAgriculture and Allied IndustriesAuto ComponentsAutomobilesAviationAyushBankingBiotechnologyCementChemicalsConsumer DurablesDefence ManufacturingECommerceEducation and TrainingElectric VehicleElectronics System Design  ManufacturingEngineering and Capital GoodsFinancial ServicesFMCGFood ProcessingGems and JewelleryHealthcareInfrastructureInsuranceIT  BPMManufacturingMedia and EntertainmentMedical DevicesMetals and MiningMSMEOil and GasPaper  PackagingPharmaceuticalsPortsPowerRailwaysReal EstateRenewable EnergyRetailRoadsScience and TechnologyServicesSteelTelecommunicationsTextilesTourism and HospitalityStatesUTAndaman and NicobarAndhra PradeshArunachal PradeshAssamBiharChandigarhChhattisgarhDadra  Nagar Haveli and Daman  DiuDelhiGoaGujaratHaryanaHimachal PradeshJammu and KashmirJharkhandKarnatakaKeralaLadakhLakshadweepMadhya PradeshMaharashtraManipurMeghalayaMizoramNagalandOdishaPuducherryPunjabRajasthanSikkimTamil NaduTelanganaTripuraUttar PradeshUttarakhandWest BengalExportsExport By ProductsExport By CountryAgriculture and FoodApparelCarpetsCashewChemicalsCoconutCoffeeCoirCottonElectronic and Computer SoftwareEngineeringGems and JewelleryHandicraftsHandloomJuteLeatherMarine ProductsOilseedsPharmaceuticalPlasticsPowerloomServicesShellac and Forest ProductsSilkSpicesSportsSynthetic and Rayon TextilesTeaTobaccoWoolWool and WoollenAustraliaBangladeshBelgiumCanadaChinaFranceGermanyHong KongIndonesiaIsraelItalyJapanKoreaMalaysiaNetherlandsRussiaSaudi ArabiaSingaporeSouth AfricaThailandTurkeyUAEUKUSVietnamBlogContactMoreResearchCase StudiesEXIM ProcedureMedia  EventsEventsFilmsImage GalleryMedia CoveragePostersOther LinksTendersArchiveCampaignsDiscover IndiaBasmati RiceIndian MilletsOrganic ProductsIndian FruitsIndian TeaBharat Mobility GI of IndiaExperience IndiaRetail Industry in IndiaIndias ecommerce sector is expected to reach US . billion in  with an annual growth rate of . to reach  US . billion by .Explore Other IndustriesAgriculture and Allied IndustriesAuto ComponentsAutomobilesAviationAyushBankingBiotechnologyCementChemicalsConsumer DurablesDefence ManufacturingECommerceEducation and TrainingElectric VehicleElectronics System Design  ManufacturingEngineering and Capital GoodsFinancial ServicesFMCGFood ProcessingGems and JewelleryHealthcareInfrastructureInsuranceIT  BPMManufacturingMedia and EntertainmentMedical DevicesMetals and MiningMSMEOil and GasPaper  PackagingPharmaceuticalsPortsPowerRailwaysReal EstateRenewable EnergyRetailRoadsScience and TechnologyServicesSteelTelecommunicationsTextilesTourism and HospitalityAdvantage IndiaRobustDemandReliance Industries Indias largest retailer stated that the country is set to emerge as the worlds thirdlargest retail market by  supported by government initiatives aimed at enhancing disposable incomes and driving consumption.Indias retail sector leasing reached over  million square feet in Q  driving total retail leasing to a record . million square feet in  across the top seven cities. DelhiNCR led the leasing with new mall constructions facilitating new store openings in key micro markets. DC brands are expanding their physical presence in fashion apparel jewellery cosmetics and wellness categories.As of FY Indias has the third highest number of eretail shoppers globally.InnovationIn FinancingCollective efforts of financial houses and banks with retailers are enabling consumers to go for durable products with easy credit.Indias consumer and retail sector recorded  deals worth US . billion in Q  with deal volume rising  sequentially and deal value declining  reflecting a shift toward smaller strategic transactions. The quarter was led by domestic consolidation and outbound activity while personal care and textiles apparel  accessories together accounted for  of total deals by volume.IncreasingInvestmentsDue to Indias wealth of resources availability of labor at relatively low costs and special investment wages such tax breaks etc. foreign corporations prefer to invest here.Indias retail trading sector attracted  . crore US . billion FDIs between April December .In January  IKEA announced plans to invest over   crore US . billion in India over the next five years to expand its retail network strengthen logistics infrastructure and increase local sourcing as part of its longterm growth strategy in the Indian retail market.PolicySupportTo improve the business climate and make it simpler for foreign companies to register fully owned subsidiaries in India the Indian government has implemented a number of rules regulations and policies.SnapshotShowcaseInfographicsReportsRelated NewsLast updated Feb Retail Industry ReportFeb IntroductionThe Indian retail industry has emerged as one of the most dynamic and fastpaced sectors driven by strong consumer demand and the entry of new players. Contributing over  to the countrys GDP and around  to employment India is today the worlds thirdlargest retail market and ranked  in the World Banks Doing Business  report. With its vast middle class and largely untapped potential India continues to attract global retail giants seeking to enter highgrowth markets.Rising purchasing power especially among urban consumers is reshaping spending patterns. Branded goods across categories such as apparel cosmetics footwear watches beverages food and jewellery are increasingly becoming part of everyday consumption and lifestyle. Indias retail sector is on track to exceed US . billion by  from US . billion in  with organised retail expected to capture more than  of the total market.The sectors growth is further reinforced by expanding retail infrastructure. Indias seven largest cities alone are expected to add . million sq. ft. of new shopping mall space by  according to Anarock.Organised retail in India is projected to reach US  billion by  driven by rising disposable incomes increasing urbanisation and evolving consumer preferences according to a DeloitteRAI report.India today ranks among the most attractive destinations for retail investment supported by its demographic advantage the worlds largest population a growing middleincome segment of  million households increasing urbanisation connected rural consumers and rising household spending. The government has also introduced progressive policies and reforms to improve the business climate making it easier for foreign players to establish wholly owned subsidiaries and tap into Indias retail potential.Indias retail sector leasing reached over  million square feet in Q  driving total retail leasing to a record . million square feet in  across the top seven cities. DelhiNCR led the leasing with new mall constructions facilitating new store openings in key micro markets. DC brands are expanding their physical presence in fashion apparel jewellery cosmetics and wellness categories.Market SizeIndias direct selling industry was valued at   crore US . billion in FY reflecting the resilience of the countrys consumption story despite global challenges. By FY India had become the worlds thirdlargest eretail market by shopper base behind only China and the US. The rapid expansion of newage logistics is expected to further boost this growth with an estimated . billion DirecttoConsumer DC shipments projected by .Indias ecommerce market was valued at US . billion in  and is projected to reach US . billion by  supported by rising internet penetration digital payments and growing consumer preference for online shopping. Reliance Industries Indias largest retailer has highlighted that the country is poised to emerge as the worlds thirdlargest retail market by  with government initiatives aimed at boosting disposable incomes and driving consumption. The ecommerce ecosystem is also witnessing parallel growth in infrastructure. The India ecommerce warehousing market size reached US . billion in  and expected to reach US . billion by  exhibiting a growth rate CAGR of . during . Indias broader digital economy is projected to touch   crore US  billion by  up from   crore US  billion in  while employing nearly . million workers.Investments DevelopmentsThe Retail sector in India has seen a lot of investments and developments in the recent past.Indias fastest consumer growth is coming from TierII and TierIII cities which are adding nearly  million new consumers to branded and organised retail by . The rise of these cities is driving national consumption patterns digital payments and the expansion of DC brands with faster trial and repeat purchases.Indias retail sector leasing reached over  million square feet in Q  driving total retail leasing to a record . million square feet in  across the top seven cities. DelhiNCR led the leasing with new mall constructions facilitating new store openings in key micro markets. DC brands are expanding their physical presence in fashion apparel jewellery cosmetics and wellness categories.Indias retail sector continued to witness strong expansion in  with retailers opening new stores across multiple formats and categories supported by rising investments expanding mall supply and growing consumer demand across major cities.Indias retail market is poised to reach US  trillion by . This growth is driven by rising incomes faster digital adoption and the rise of an aspirational consumer class. New retail formats like ecommerce quick commerce and DC brands are scaling faster than conventional companies indicating a structural shift in shopping habits and huge investor interest.In January  IKEA announced plans to invest over   crore US . billion in India over the next five years to expand its retail network strengthen logistics infrastructure and increase local sourcing as part of its longterm growth strategy in the Indian retail market.Indias luxury retail market continued to witness strong growth in Q  with overall retail leasing reaching a record . million sq. ft. driven by rising demand from premium and luxury brands across major cities. The growth was supported by experienceled flagship stores premium retail formats and increasing affluent consumer spending.Retailers are expanding their private label offerings to meet this demand. For instance Reliance Retail is intensifying its focus on private labels in the consumer durables sector aiming to challenge established global brands.A report by EY indicates that  of Indian consumers are opting for private label products in  with  acknowledging that these brands are increasingly offering better quality products.AstorMueller AG has entered Indias retail market through a joint venture with Gaurik Group called Nuvora aiming to launch  to  exclusive Bugatti stores across the top  cities in FY.According to Bain  Companys  eretail report Indias online retail market is witnessing a gradual shift from cashondelivery COD to digital payment modes such as UPIbased payments at delivery reflecting rising adoption of digital transactions across online shopping platforms.In January  Xiaomi said  of its phones and TVs sold in India are manufactured locally while wearables and tablets are also made in India local sourcing has risen to about  of its components.In November  Lush reentered India through a licensing partnership with Bilberry Brands starting online and planning physical stores in key cities such as New Delhi Mumbai and Bengaluru.In December  Prada announced a limitededition Made in India Kolhapuriinspired sandal collection set to launch in February  across  global stores and online in collaboration with Indian artisan bodies.In December  lululemon announced plans to expand into six new international markets in  including India through a partnership with Tata CLiQ with the brand set to launch through Tata CLiQ Luxury and Tata CLiQ Fashion platforms alongside its first physical store in the country.In FY Zudio more than doubled its store count from approximately  to  outlets across  cities driving its milestone of over   crore US  billion in revenue.In  over  global brands entered India underscoring the countrys growing appeal for international retailers and premium consumer brands.In February  Nykaa opened  new stores and entered four new cities in Q FY taking its total store count to .In January  Tim Hortons India opened two new outlets at Navi Mumbai International Airport strengthening its presence across highfootfall transit locations.In January  IKEA said it will invest over   crores US . billion in India over the next five years to expand its retail network logistics and local sourcing.In November  LuLu Group revived its Visakhapatnam mall project after signing a fresh MoU with the Andhra Pradesh government with the project expected to create new direct and indirect jobs.As of November  Reliance Retail operates  stores across with a retail area of over . million sq. ft. in India.In February  Indias CPI inflation stood at . provisional with rural inflation at . and urban inflation at . while food inflation was ..Indias retail trading sector attracted  . crore US . billion FDIs between April December .Indias consumer and retail sector recorded  deals worth US . billion in Q  with deal volume rising  sequentially and deal value declining  reflecting a shift toward smaller strategic transactions. The quarter was led by domestic consolidation and outbound activity while personal care and textiles apparel  accessories together accounted for  of total deals by volume.By  Indias per capita income is expected to exceed   US  from  US  in FY unlocking new business opportunities across sectors. Expanding digital commerce growing access to credit and fintechdriven financial inclusion further accelerate this consumption boom.Indias   crore US  billion cosmetics and beauty market are poised to benefit from the IndiaUK free trade agreement FTA which will reduce duties on cosmetics and other products. The FTA will directly benefit retailers like Nykaa Reliance Tira and Shoppers Stop as well as ecommerce platforms like Amazon and Myntra which sell premium beauty products.Indias private final consumption expenditure PFCE is estimated at   crore US . billion in FY First Advance Estimates growing . over the previous year and accounting for . of GDP. As per Economic Survey  PFCE will grew . in FY supported by low inflation stable employment and rising real purchasing power.Indias seven major cities are set to receive . million square feet sq. ft. of prime retail space in new shopping malls by the end of  as per Anarocks data.In February  Hindustan Unilever approved the acquisition of the remaining  stake in Zywie Ventures OZiva for   crore US . million and the divestment of its . stake in Nutritionalab for   crore US . million strengthening its health and wellbeing portfolio.In February  Reliance Consumer Products acquired  equity stake in Southern Health Foods Private Limited maker of the Manna brand for  . crore US . million adding to its health foods and staples portfolio.French sports retailer Decathlon is accelerating its investments to ramp up production and enhance its retail presence further in India.In February  Trent said it had added over  stores in the nine months to December  taking its total store count to more than  and accelerating expansion in smaller towns and suburban markets.Reliance Industries is likely to sell another  stake in Reliance Retail Ventures Ltd RRVL to fund expansion retire debt and prepare for the initial public offering of the conglomerates retail business.Reliance Consumer Products the FMCG arm of Reliance Retail announced the launch of it madeforIndia consumer packaged goods brand Independence in Gujarat.Retail tech companies supporting the retail sector with services such as digital ledgers inventory management payments solutions and tools for logistics and fulfilment are taking off in India.With the rising need for consumer goods in different sectors including consumer electronics and home appliances many companies have invested in the Indian retail space in the past few months.Growth Drivers for retail in IndiaGold loans are driving Indias retail credit growth rising  YoY to   crore US . trillion in FY boosted by higher gold values and easier credit from public sector banks and NBFCs.From FY to FY digital transactions have surged exceeding  crore in number and totalling more than   crore US  trillion.As of February  UPI transactions reached . billion worth  . lakh crore US . billion registering a  yearonyear growth in transaction volume and a  increase in transaction value reflecting rapid growth in digital payment adoption across retail merchant outlets.Favourable Demographics Indias large and young population Rising Middle Class Urbanization Changing Lifestyle and Consumption Patterns and favourable government initiatives prove to be a growth engine for the retail industry.Change in consumer mindset The transition from traditional retail to online platforms in India has spurred a shift in consumer mindset. This change is characterized by a prioritization of convenience a wider product selection increased price sensitivity growing trust in online transactions reliance on reviews and recommendations evolving loyalty dynamics a greater embrace of technology and heightened expectations for fast delivery. A new CBRE  Invest India survey has revealed a significant shift in Indias retail landscape driven by a growing consumer demand for experiencebased entertainment. Over  of respondents across various age groups prefer participatory activities such as bowling amusement parks rock climbing escape rooms and childrens play zones over passive options like museums or art exhibitions. Minisized beauty products are gaining traction in India driven by affordability convenience and the desire for experimentation particularly among Gen Z. These small packs often called minis are reshaping the Indian beauty market as more consumers look to experiment with makeup at the right price.Brand consciousness Brand consciousness in India is a multifaceted phenomenon shaped by economic cultural and technological factors. As consumer expectations continue to evolve brands must remain agile and responsive to changing trends ensuring that they deliver value innovation and authenticity to maintain their competitive edge in the market.Government InitiativesThe Government of India has taken various initiatives to improve the retail industry in India. Some of them are listed belowIn December  the Government of India said the seven PM MITRA Parks are expected to attract nearly   crore US . billion in investments and generate around  lakh employment opportunities aimed at strengthening integrated retail and textile manufacturing ecosystems across multiple states.Government may change Foreign Direct Investment FDI rules in food processing in a bid to permit Ecommerce companies and foreign retailers to sell Made in India consumer products.Government of India has allowed  FDI in online retail of goods and services through the automatic route thereby providing clarity on the existing businesses of Ecommerce companies operating in India.Road AheadConsumer preferences and buying behaviours in India are evolving rapidly driven by greater access to technology and digital platforms. Shoppers increasingly expect seamless experiences across offline and online channels prompting retailers to design integrated strategies that combine traditional stores with ecommerce platforms. Companies are also exploring innovat

In [14]:
nltk.download('punkt_tab')
tokens = nltk.word_tokenize(retailtxt)
display(tokens[:10])

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\newta\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

['Retail',
 'Industry',
 'in',
 'India',
 'Overview',
 'of',
 'Retail',
 'Sector',
 'Market',
 'Size']

In [15]:

# Web Scrape Data | | V Data Preprocessing - Remove punctuations, digits, special characters | | Tokenization - Breaking text into words or tokens. Default delimiter is space. || Vectorization - converting words/tokens to matrix of numbers.

In [16]:
from nltk.tokenize import word_tokenize

In [17]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\newta\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [18]:
retail_words = word_tokenize(retailtxt.lower())

In [19]:
type(retail_words)

list

In [20]:
retail_words = [w for w in retail_words if w.isalnum()]

# isalnum() to select only words

In [21]:
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\newta\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [22]:
english_stopwords = set(stopwords.words('english'))

In [23]:
english_stopwords

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [24]:
retail_words = [w for w in retail_words if w not in english_stopwords]

In [25]:
retail_words[0:20]

['retail',
 'industry',
 'india',
 'overview',
 'retail',
 'sector',
 'market',
 'size',
 'growth',
 'ibefloginhomeabout',
 'usannual',
 'reportsboard',
 'trusteescareerstendersindian',
 'economydomestic',
 'investmentseconomic',
 'survey',
 'export',
 'promotion',
 'missionforeign',
 'direct']

In [26]:
retail_words = [w for w in retail_words if len(w) > 2]

In [27]:
len(retail_words)

2166

In [28]:
from nltk.probability import FreqDist

In [29]:
word_freq = FreqDist(retail_words)

In [30]:
word_freq.most_common(20)

[('retail', 67),
 ('india', 37),
 ('billion', 32),
 ('indias', 30),
 ('consumer', 22),
 ('market', 21),
 ('new', 20),
 ('growth', 19),
 ('crore', 19),
 ('million', 18),
 ('across', 18),
 ('rising', 17),
 ('sector', 16),
 ('digital', 16),
 ('cities', 14),
 ('leasing', 12),
 ('industry', 11),
 ('brands', 11),
 ('driven', 11),
 ('growing', 10)]

In [31]:
from sklearn.feature_extraction.text import CountVectorizer

In [32]:
dtm = CountVectorizer(max_features = 30, stop_words = "english") # Convert to document term matrix

In [33]:
X_Dtm = dtm.fit_transform(retail_words)

In [34]:
pd.DataFrame(X_Dtm.toarray(), columns = dtm.get_feature_names_out()).head()

,billion,brands,cities,consumer,consumption,crore,digital,driven,ecommerce,expanding,...,new,online,reach,reliance,retail,rising,sector,store,stores,total
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0

In [35]:
# Second vertorization
from sklearn.feature_extraction.text import TfidfVectorizer

In [36]:
tfidf = TfidfVectorizer(max_features=30, stop_words = "english")

In [37]:
X_tfidf = tfidf.fit_transform(retail_words)

In [38]:
pd.DataFrame(X_tfidf.toarray(), columns = tfidf.get_feature_names_out()).head()

,billion,brands,cities,consumer,consumption,crore,digital,driven,ecommerce,expanding,...,new,online,reach,reliance,retail,rising,sector,store,stores,total
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [39]:
# LLM Models particularly Generative AI Models fail to work with sparse matrices like
# Document Term Matrix & Term frequence Inverse Document frequency Matrix

# EMbedding or vector embedding were created for LLMs.
# 5 Dimensional embedding for word cat
# cat = [0.2, 0.8, 0.1, -0.5, 0.3]

In [40]:
 # !pip install transformers

In [41]:
from transformers import GPT2LMHeadModel, GPT2Tokenizer

In [42]:
tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
model = GPT2LMHeadModel.from_pretrained("gpt2")

# a) config_json - Neural network model architecture , number of hidden layer, hidden dimensions , attention head

# b) model.safetensors - Brain of model life containing trained weights and paramaters

# c) loading_weights - transformer library successfully loaded model weishts

# d) generation_config_json - how model should generate text

# e) tokenizer's jsons - for tokening text

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

C:\Users\newta\anaconda3\Lib\site-packages\huggingface_hub\file_download.py:129: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\newta\.cache\huggingface\hub\models--gpt2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

In [43]:
# Prompt is a method t interact with LLM. Prompt can be text, image, document, etc.

In [44]:
prompt = "What is the capital of India considering Paris is capital of France"

In [45]:
inputs = tokenizer.encode(prompt, return_tensors = "pt")
print(inputs)

tensor([[2061,  318,  262, 3139,  286, 3794, 6402, 6342,  318, 3139,  286, 4881]])

In [46]:
embeddings = model.transformer.wte(inputs)
print(embeddings)

tensor([[[ 0.0090, -0.0207,  0.0244,  ...,  0.2356, -0.0294,  0.1107],
         [-0.0097,  0.0101,  0.0556,  ...,  0.1145, -0.0380, -0.0254],
         [-0.0393,  0.0050,  0.0421,  ..., -0.0477,  0.0670, -0.0471],
         ...,
         [ 0.0573, -0.0070,  0.0914,  ...,  0.0372, -0.0265,  0.0640],
         [-0.0572,  0.0183,  0.0333,  ..., -0.0689, -0.0931, -0.0714],
         [-0.0694,  0.0489,  0.1624,  ..., -0.1486,  0.0900, -0.0894]]],
       grad_fn=<EmbeddingBackward0>)

In [47]:
# Decoding
output = model.generate(inputs, max_length = 20, num_return_sequences = 1, no_repeat_ngram_size = 2, early_stopping = True)

The following generation flags are not valid and may be ignored: ['early_stopping']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.

In [48]:
output

tensor([[2061,  318,  262, 3139,  286, 3794, 6402, 6342,  318, 3139,  286, 4881,
           30,  198,  198,  464, 3139,  318, 6342,   13]])

In [49]:
response = tokenizer.decode(output[0], skip_special_tokens = True)

In [50]:
response

'What is the capital of India considering Paris is capital of France?\n\nThe capital is Paris.'

In [51]:
# GPT2 Models are with context models. search for answers from the trained text only
# and context must be provided for these models to perform
# Context means it should get a relevance.
# Context means an example of expected answer must be provided.
# Context window is how much text model should remember at once.
# Smaller context window forgets earlier text.
# Larger context window understands context better as long sequences are memorised.

In [52]:
# Without context,  models are trained on large scale data like world wide web and
# memorize their learning during training phase entirely.
# Context model will just resort to the data we provide for training.

In [53]:
# Use WITHOUT CONTEXT MODEL

In [54]:
from transformers import pipeline

In [55]:
# Initiate text generation pipeline
generator = pipeline("text-generation", model = "TinyLlama/TinyLlama-1.1B-Chat-v1.0")

config.json:   0%|          | 0.00/608 [00:00<?, ?B/s]

C:\Users\newta\anaconda3\Lib\site-packages\huggingface_hub\file_download.py:129: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\newta\.cache\huggingface\hub\models--TinyLlama--TinyLlama-1.1B-Chat-v1.0. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

model.safetensors:   0%|          | 0.00/2.20G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/551 [00:00<?, ?B/s]

In [56]:
#Define the prompt
prompt = "Question: What is the capital of India\nAnswer"

In [57]:
outputs = generator(prompt,max_new_tokens = 20, do_sample=False)

The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Passing `generation_config` together with generation-related arguments=({'max_new_tokens', 'do_sample'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
Both `max_new_tokens` (=20) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

In [58]:
print(outputs[0]['generated_text'])

Question: What is the capital of India
Answer: The capital of India is New Delhi.

Based on the text material, what

In [59]:
# max_new_tokens - how many output tokens and words to be generated

In [60]:
sentiment_pipeline = pipeline("sentiment-analysis")

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f.
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

C:\Users\newta\anaconda3\Lib\site-packages\huggingface_hub\file_download.py:129: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\newta\.cache\huggingface\hub\models--distilbert--distilbert-base-uncased-finetuned-sst-2-english. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

In [61]:
sentiment_pipeline("There are far scarier movies than Obsession. However, the movie definitely succeeds at being unnerving, even if it isn’t the type of story that will strike a deep fear within you.")

[{'label': 'POSITIVE', 'score': 0.998223602771759}]

In [62]:
# Questions for tomorrow

# 1) in normal NLP/Text processing before Gen AI, we had no use of the embeddings. We could directly take the tf-idf and feed it to a ML/AI Algorithm
# 2) in the Gen AI, encoder gives us token which in turn gives us the dimensional array. basically the encoder neural network does all this.
# 3) context model which runs on local, do they have local vector databases. also does every chatGPT Applicaiton instance have 2 neural nets and do they have a remote common database?
# 4) whaty is the assurance that when we use a conbtext model, it wont search the internet
# 5) What we used esterday, there was no attention at all. also word2Vec used in NLP or gen AI too? also will ML/DL get useless with genAI?