In [1]:
import os
import pandas as pd
import numpy as np

In [2]:
os.listdir(".")

['.ipynb_checkpoints', 'data.csv', 'Jupyter.ipynb']

In [3]:
df = pd.read_csv('data.csv')

In [4]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [6]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [7]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [16]:
df['Review Rating']

0       3.1
1       3.1
2       3.1
3       3.5
4       2.7
       ...
3895    4.2
3896    4.5
3897    2.9
3898    3.8
3899    3.1
Name: Review Rating, Length: 3900, dtype: float64

In [18]:
category_medians = df.groupby('Category')['Review Rating'].median()
print(category_medians)

Category
Accessories    3.8
Clothing       3.7
Footwear       3.8
Outerwear      3.8
Name: Review Rating, dtype: float64

In [19]:
type(category_medians)

pandas.core.series.Series

In [20]:
df['Review Rating'] = df['Review Rating'].fillna(df['Category'].map(category_medians))

In [21]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [22]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases'],
      dtype='object')

In [23]:
df.columns.str.lower()

Index(['customer id', 'age', 'gender', 'item purchased', 'category',
       'purchase amount (usd)', 'location', 'size', 'color', 'season',
       'review rating', 'subscription status', 'shipping type',
       'discount applied', 'promo code used', 'previous purchases',
       'payment method', 'frequency of purchases'],
      dtype='object')

In [24]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [25]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

#### The "q" in qcut stands for Quantile. While a standard "cut" looks at specific values (like 0-20, 21-40), qcut looks at the distribution of your data. It tries to divide the data so that approximately the same number of rows end up in each group.

In [28]:
df['age'].value_counts()

age
69    88
57    87
41    86
25    85
49    84
50    83
54    83
27    83
62    83
32    82
19    81
58    81
42    80
43    79
28    79
31    79
37    77
46    76
29    76
68    75
59    75
63    75
56    74
36    74
55    73
52    73
64    73
35    72
51    72
65    72
40    72
45    72
47    71
66    71
30    71
23    71
38    70
53    70
18    69
21    69
26    69
34    68
48    68
24    68
39    68
70    67
22    66
61    65
60    65
33    63
20    62
67    54
44    51
Name: count, dtype: int64

In [29]:
# create a new column age_group
labels = ['Young Adult', 'Adult', 'Middle-aged', 'Senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels = labels)

In [30]:
df[['age','age_group']].head(10)

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-aged

### Create new column purchase_frequency_days

In [31]:
frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [32]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

In [33]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [34]:

(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [35]:
# Dropping promo code used column

df = df.drop('promo_code_used', axis=1)

In [36]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [37]:
pip install psycopg2-binary sqlalchemy

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp313-cp313-win_amd64.whl.metadata (5.1 kB)
Requirement already satisfied: sqlalchemy in c:\users\newta\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\users\newta\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\newta\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp313-cp313-win_amd64.whl (2.7 MB)
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.7 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.7 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.7 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.7 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.7 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.7 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.7 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.7 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.7 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.7 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.7 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.7 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.7 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.7 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.7 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.7 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.7 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.7 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.7 MB ? eta -:--:--
   ------- -------------------------------- 0.5/2.7 MB 66.7 kB/s eta 0:00:33
   ------- -------------------------------- 0.5/2.7 MB 66.7 kB/s eta 0:00:33
   ------- -------------------------------- 0.5/2.7 MB 66.7 kB/s eta 0:00:33
   ------- -------------------------------- 0.5/2.7 MB 66.7 kB/s eta 0:00:33
   ------- -------------------------------- 0.5/2.7 MB 66.7 kB/s eta 0:00:33
   ------- -------------------------------- 0.5/2.7 MB 66.7 kB/s eta 0:00:33
   ------- -------------------------------- 0.5/2.7 MB 66.7 kB/s eta 0:00:33
   ------- -------------------------------- 0.5/2.7 MB 66.7 kB/s eta 0:00:33
   ------- -------------------------------- 0.5/2.7 MB 66.7 kB/s eta 0:00:33
   ------- -------------------------------- 0.5/2.7 MB 66.7 kB/s eta 0:00:33
   ------- -------------------------------- 0.5/2.7 MB 66.7 kB/s eta 0:00:33
   ------- -------------------------------- 0.5/2.7 MB 66.7 kB/s eta 0:00:33
   ------- -------------------------------- 0.5/2.7 MB 66.7 kB/s eta 0:00:33
   ------- -------------------------------- 0.5/2.7 MB 66.7 kB/s eta 0:00:33
   ------- -------------------------------- 0.5/2.7 MB 66.7 kB/s eta 0:00:33
   ------- -------------------------------- 0.5/2.7 MB 66.7 kB/s eta 0:00:33
   ------- -------------------------------- 0.5/2.7 MB 66.7 kB/s eta 0:00:33
   ------- -------------------------------- 0.5/2.7 MB 66.7 kB/s eta 0:00:33
   ------- -------------------------------- 0.5/2.7 MB 66.7 kB/s eta 0:00:33
   ------- -------------------------------- 0.5/2.7 MB 66.7 kB/s eta 0:00:33
   ------- -------------------------------- 0.5/2.7 MB 66.7 kB/s eta 0:00:33
   ------- -------------------------------- 0.5/2.7 MB 66.7 kB/s eta 0:00:33
   ------- -------------------------------- 0.5/2.7 MB 66.7 kB/s eta 0:00:33
   ------- -------------------------------- 0.5/2.7 MB 66.7 kB/s eta 0:00:33
   ------- -------------------------------- 0.5/2.7 MB 66.7 kB/s eta 0:00:33
   ----------- ---------------------------- 0.8/2.7 MB 57.6 kB/s eta 0:00:34
   ----------- ---------------------------- 0.8/2.7 MB 57.6 kB/s eta 0:00:34
   ----------- ---------------------------- 0.8/2.7 MB 57.6 kB/s eta 0:00:34
   ----------- ---------------------------- 0.8/2.7 MB 57.6 kB/s eta 0:00:34
   ----------- ---------------------------- 0.8/2.7 MB 57.6 kB/s eta 0:00:34
   ----------- ---------------------------- 0.8/2.7 MB 57.6 kB/s eta 0:00:34
   ----------- ---------------------------- 0.8/2.7 MB 57.6 kB/s eta 0:00:34
   ----------- ---------------------------- 0.8/2.7 MB 57.6 kB/s eta 0:00:34
   ----------- ---------------------------- 0.8/2.7 MB 57.6 kB/s eta 0:00:34
   ----------- ---------------------------- 0.8/2.7 MB 57.6 kB/s eta 0:00:34
   ----------- ---------------------------- 0.8/2.7 MB 57.6 kB/s eta 0:00:34
   ----------- ---------------------------- 0.8/2.7 MB 57.6 kB/s eta 0:00:34
   ----------- ---------------------------- 0.8/2.7 MB 57.6 kB/s eta 0:00:34
   ----------- ---------------------------- 0.8/2.7 MB 57.6 kB/s eta 0:00:34
   ----------- ---------------------------- 0.8/2.7 MB 57.6 kB/s eta 0:00:34
   ----------- ---------------------------- 0.8/2.7 MB 57.6 kB/s eta 0:00:34
   ----------- ---------------------------- 0.8/2.7 MB 57.6 kB/s eta 0:00:34
   ----------- ---------------------------- 0.8/2.7 MB 57.6 kB/s eta 0:00:34
   ----------- ---------------------------- 0.8/2.7 MB 57.6 kB/s eta 0:00:34
   ----------- ---------------------------- 0.8/2.7 MB 57.6 kB/s eta 0:00:34
   ----------- ---------------------------- 0.8/2.7 MB 57.6 kB/s eta 0:00:34
   ----------- ---------------------------- 0.8/2.7 MB 57.6 kB/s eta 0:00:34
   ----------- ---------------------------- 0.8/2.7 MB 57.6 kB/s eta 0:00:34
   ----------- ---------------------------- 0.8/2.7 MB 57.6 kB/s eta 0:00:34
   ----------- ---------------------------- 0.8/2.7 MB 57.6 kB/s eta 0:00:34
   ----------- ---------------------------- 0.8/2.7 MB 57.6 kB/s eta 0:00:34
   ----------- ---------------------------- 0.8/2.7 MB 57.6 kB/s eta 0:00:34
   ----------- ---------------------------- 0.8/2.7 MB 57.6 kB/s eta 0:00:34
   ----------- ---------------------------- 0.8/2.7 MB 57.6 kB/s eta 0:00:34
   ----------- ---------------------------- 0.8/2.7 MB 57.6 kB/s eta 0:00:34
   ----------- ---------------------------- 0.8/2.7 MB 57.6 kB/s eta 0:00:34
   --------------- ------------------------ 1.0/2.7 MB 50.5 kB/s eta 0:00:33
   --------------- ------------------------ 1.0/2.7 MB 50.5 kB/s eta 0:00:33
   --------------- ------------------------ 1.0/2.7 MB 50.5 kB/s eta 0:00:33
   --------------- ------------------------ 1.0/2.7 MB 50.5 kB/s eta 0:00:33
   --------------- ------------------------ 1.0/2.7 MB 50.5 kB/s eta 0:00:33
   --------------- ------------------------ 1.0/2.7 MB 50.5 kB/s eta 0:00:33
   --------------- ------------------------ 1.0/2.7 MB 50.5 kB/s eta 0:00:33
   --------------- ------------------------ 1.0/2.7 MB 50.5 kB/s eta 0:00:33
   --------------- ------------------------ 1.0/2.7 MB 50.5 kB/s eta 0:00:33
   --------------- ------------------------ 1.0/2.7 MB 50.5 kB/s eta 0:00:33
   --------------- ------------------------ 1.0/2.7 MB 50.5 kB/s eta 0:00:33
   --------------- ------------------------ 1.0/2.7 MB 50.5 kB/s eta 0:00:33
   --------------- ------------------------ 1.0/2.7 MB 50.5 kB/s eta 0:00:33
   --------------- ------------------------ 1.0/2.7 MB 50.5 kB/s eta 0:00:33
   --------------- ------------------------ 1.0/2.7 MB 50.5 kB/s eta 0:00:33
   --------------- ------------------------ 1.0/2.7 MB 50.5 kB/s eta 0:00:33
   --------------- ------------------------ 1.0/2.7 MB 50.5 kB/s eta 0:00:33
   --------------- ------------------------ 1.0/2.7 MB 50.5 kB/s eta 0:00:33
   --------------- ------------------------ 1.0/2.7 MB 50.5 kB/s eta 0:00:33
   --------------- ------------------------ 1.0/2.7 MB 50.5 kB/s eta 0:00:33
   --------------- ------------------------ 1.0/2.7 MB 50.5 kB/s eta 0:00:33
   --------------- ------------------------ 1.0/2.7 MB 50.5 kB/s eta 0:00:33
   --------------- ------------------------ 1.0/2.7 MB 50.5 kB/s eta 0:00:33
   --------------- ------------------------ 1.0/2.7 MB 50.5 kB/s eta 0:00:33
   --------------- ------------------------ 1.0/2.7 MB 50.5 kB/s eta 0:00:33
   --------------- ------------------------ 1.0/2.7 MB 50.5 kB/s eta 0:00:33
   --------------- ------------------------ 1.0/2.7 MB 50.5 kB/s eta 0:00:33
   ------------------- -------------------- 1.3/2.7 MB 49.4 kB/s eta 0:00:29
   ------------------- -------------------- 1.3/2.7 MB 49.4 kB/s eta 0:00:29
   ------------------- -------------------- 1.3/2.7 MB 49.4 kB/s eta 0:00:29
   ------------------- -------------------- 1.3/2.7 MB 49.4 kB/s eta 0:00:29
   ------------------- -------------------- 1.3/2.7 MB 49.4 kB/s eta 0:00:29
   ------------------- -------------------- 1.3/2.7 MB 49.4 kB/s eta 0:00:29
   ------------------- -------------------- 1.3/2.7 MB 49.4 kB/s eta 0:00:29
   ------------------- -------------------- 1.3/2.7 MB 49.4 kB/s eta 0:00:29
   ------------------- -------------------- 1.3/2.7 MB 49.4 kB/s eta 0:00:29
   ------------------- -------------------- 1.3/2.7 MB 49.4 kB/s eta 0:00:29
   ------------------- -------------------- 1.3/2.7 MB 49.4 kB/s eta 0:00:29
   ------------------- -------------------- 1.3/2.7 MB 49.4 kB/s eta 0:00:29
   ------------------- -------------------- 1.3/2.7 MB 49.4 kB/s eta 0:00:29
   ------------------- -------------------- 1.3/2.7 MB 49.4 kB/s eta 0:00:29
   ------------------- -------------------- 1.3/2.7 MB 49.4 kB/s eta 0:00:29
   ------------------- -------------------- 1.3/2.7 MB 49.4 kB/s eta 0:00:29
   ------------------- -------------------- 1.3/2.7 MB 49.4 kB/s eta 0:00:29
   ------------------- -------------------- 1.3/2.7 MB 49.4 kB/s eta 0:00:29
   ------------------- -------------------- 1.3/2.7 MB 49.4 kB/s eta 0:00:29
   ------------------- -------------------- 1.3/2.7 MB 49.4 kB/s eta 0:00:29
   ------------------- -------------------- 1.3/2.7 MB 49.4 kB/s eta 0:00:29
   ------------------- -------------------- 1.3/2.7 MB 49.4 kB/s eta 0:00:29
   ------------------- -------------------- 1.3/2.7 MB 49.4 kB/s eta 0:00:29
   ------------------- -------------------- 1.3/2.7 MB 49.4 kB/s eta 0:00:29
   ----------------------- ---------------- 1.6/2.7 MB 49.8 kB/s eta 0:00:23
   ----------------------- ---------------- 1.6/2.7 MB 49.8 kB/s eta 0:00:23
   ----------------------- ---------------- 1.6/2.7 MB 49.8 kB/s eta 0:00:23
   ----------------------- ---------------- 1.6/2.7 MB 49.8 kB/s eta 0:00:23
   ----------------------- ---------------- 1.6/2.7 MB 49.8 kB/s eta 0:00:23
   ----------------------- ---------------- 1.6/2.7 MB 49.8 kB/s eta 0:00:23
   ----------------------- ---------------- 1.6/2.7 MB 49.8 kB/s eta 0:00:23
   ----------------------- ---------------- 1.6/2.7 MB 49.8 kB/s eta 0:00:23
   ----------------------- ---------------- 1.6/2.7 MB 49.8 kB/s eta 0:00:23
   ----------------------- ---------------- 1.6/2.7 MB 49.8 kB/s eta 0:00:23
   ----------------------- ---------------- 1.6/2.7 MB 49.8 kB/s eta 0:00:23
   ----------------------- ---------------- 1.6/2.7 MB 49.8 kB/s eta 0:00:23
   ----------------------- ---------------- 1.6/2.7 MB 49.8 kB/s eta 0:00:23
   ----------------------- ---------------- 1.6/2.7 MB 49.8 kB/s eta 0:00:23
   ----------------------- ---------------- 1.6/2.7 MB 49.8 kB/s eta 0:00:23
   ----------------------- ---------------- 1.6/2.7 MB 49.8 kB/s eta 0:00:23
   ----------------------- ---------------- 1.6/2.7 MB 49.8 kB/s eta 0:00:23
   ----------------------- ---------------- 1.6/2.7 MB 49.8 kB/s eta 0:00:23
   ----------------------- ---------------- 1.6/2.7 MB 49.8 kB/s eta 0:00:23
   ----------------------- ---------------- 1.6/2.7 MB 49.8 kB/s eta 0:00:23
   --------------------------- ------------ 1.8/2.7 MB 49.5 kB/s eta 0:00:18
   --------------------------- ------------ 1.8/2.7 MB 49.5 kB/s eta 0:00:18
   --------------------------- ------------ 1.8/2.7 MB 49.5 kB/s eta 0:00:18
   --------------------------- ------------ 1.8/2.7 MB 49.5 kB/s eta 0:00:18
   --------------------------- ------------ 1.8/2.7 MB 49.5 kB/s eta 0:00:18
   --------------------------- ------------ 1.8/2.7 MB 49.5 kB/s eta 0:00:18
   --------------------------- ------------ 1.8/2.7 MB 49.5 kB/s eta 0:00:18
   --------------------------- ------------ 1.8/2.7 MB 49.5 kB/s eta 0:00:18
   --------------------------- ------------ 1.8/2.7 MB 49.5 kB/s eta 0:00:18
   --------------------------- ------------ 1.8/2.7 MB 49.5 kB/s eta 0:00:18
   --------------------------- ------------ 1.8/2.7 MB 49.5 kB/s eta 0:00:18
   --------------------------- ------------ 1.8/2.7 MB 49.5 kB/s eta 0:00:18
   --------------------------- ------------ 1.8/2.7 MB 49.5 kB/s eta 0:00:18
   --------------------------- ------------ 1.8/2.7 MB 49.5 kB/s eta 0:00:18
   --------------------------- ------------ 1.8/2.7 MB 49.5 kB/s eta 0:00:18
   --------------------------- ------------ 1.8/2.7 MB 49.5 kB/s eta 0:00:18
   --------------------------- ------------ 1.8/2.7 MB 49.5 kB/s eta 0:00:18
   --------------------------- ------------ 1.8/2.7 MB 49.5 kB/s eta 0:00:18
   --------------------------- ------------ 1.8/2.7 MB 49.5 kB/s eta 0:00:18
   --------------------------- ------------ 1.8/2.7 MB 49.5 kB/s eta 0:00:18
   --------------------------- ------------ 1.8/2.7 MB 49.5 kB/s eta 0:00:18
   --------------------------- ------------ 1.8/2.7 MB 49.5 kB/s eta 0:00:18
   ------------------------------ --------- 2.1/2.7 MB 50.5 kB/s eta 0:00:13
   ------------------------------ --------- 2.1/2.7 MB 50.5 kB/s eta 0:00:13
   ------------------------------ --------- 2.1/2.7 MB 50.5 kB/s eta 0:00:13
   ------------------------------ --------- 2.1/2.7 MB 50.5 kB/s eta 0:00:13
   ------------------------------ --------- 2.1/2.7 MB 50.5 kB/s eta 0:00:13
   ------------------------------ --------- 2.1/2.7 MB 50.5 kB/s eta 0:00:13
   ------------------------------ --------- 2.1/2.7 MB 50.5 kB/s eta 0:00:13
   ------------------------------ --------- 2.1/2.7 MB 50.5 kB/s eta 0:00:13
   ------------------------------ --------- 2.1/2.7 MB 50.5 kB/s eta 0:00:13
   ------------------------------ --------- 2.1/2.7 MB 50.5 kB/s eta 0:00:13
   ------------------------------ --------- 2.1/2.7 MB 50.5 kB/s eta 0:00:13
   ------------------------------ --------- 2.1/2.7 MB 50.5 kB/s eta 0:00:13
   ------------------------------ --------- 2.1/2.7 MB 50.5 kB/s eta 0:00:13
   ------------------------------ --------- 2.1/2.7 MB 50.5 kB/s eta 0:00:13
   ------------------------------ --------- 2.1/2.7 MB 50.5 kB/s eta 0:00:13
   ------------------------------ --------- 2.1/2.7 MB 50.5 kB/s eta 0:00:13
   ------------------------------ --------- 2.1/2.7 MB 50.5 kB/s eta 0:00:13
   ------------------------------ --------- 2.1/2.7 MB 50.5 kB/s eta 0:00:13
   ---------------------------------- ----- 2.4/2.7 MB 53.1 kB/s eta 0:00:07
   ---------------------------------- ----- 2.4/2.7 MB 53.1 kB/s eta 0:00:07
   ---------------------------------- ----- 2.4/2.7 MB 53.1 kB/s eta 0:00:07
   ---------------------------------- ----- 2.4/2.7 MB 53.1 kB/s eta 0:00:07
   ---------------------------------- ----- 2.4/2.7 MB 53.1 kB/s eta 0:00:07
   ---------------------------------- ----- 2.4/2.7 MB 53.1 kB/s eta 0:00:07
   ---------------------------------- ----- 2.4/2.7 MB 53.1 kB/s eta 0:00:07
   ---------------------------------- ----- 2.4/2.7 MB 53.1 kB/s eta 0:00:07
   ---------------------------------- ----- 2.4/2.7 MB 53.1 kB/s eta 0:00:07
   ---------------------------------- ----- 2.4/2.7 MB 53.1 kB/s eta 0:00:07
   ---------------------------------- ----- 2.4/2.7 MB 53.1 kB/s eta 0:00:07
   ---------------------------------- ----- 2.4/2.7 MB 53.1 kB/s eta 0:00:07
   ---------------------------------- ----- 2.4/2.7 MB 53.1 kB/s eta 0:00:07
   ---------------------------------- ----- 2.4/2.7 MB 53.1 kB/s eta 0:00:07
   ---------------------------------- ----- 2.4/2.7 MB 53.1 kB/s eta 0:00:07
   ---------------------------------- ----- 2.4/2.7 MB 53.1 kB/s eta 0:00:07
   ---------------------------------- ----- 2.4/2.7 MB 53.1 kB/s eta 0:00:07
   ---------------------------------- ----- 2.4/2.7 MB 53.1 kB/s eta 0:00:07
   ---------------------------------- ----- 2.4/2.7 MB 53.1 kB/s eta 0:00:07
   ---------------------------------- ----- 2.4/2.7 MB 53.1 kB/s eta 0:00:07
   ---------------------------------- ----- 2.4/2.7 MB 53.1 kB/s eta 0:00:07
   -------------------------------------- - 2.6/2.7 MB 56.7 kB/s eta 0:00:02
   -------------------------------------- - 2.6/2.7 MB 56.7 kB/s eta 0:00:02
   -------------------------------------- - 2.6/2.7 MB 56.7 kB/s eta 0:00:02
   -------------------------------------- - 2.6/2.7 MB 56.7 kB/s eta 0:00:02
   -------------------------------------- - 2.6/2.7 MB 56.7 kB/s eta 0:00:02
   -------------------------------------- - 2.6/2.7 MB 56.7 kB/s eta 0:00:02
   ---------------------------------------- 2.7/2.7 MB 57.7 kB/s  0:00:46
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
Note: you may need to restart the kernel to use updated packages.

In [38]:
!pip install pymysql sqlalchemy

Collecting pymysql
  Downloading pymysql-1.1.2-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: sqlalchemy in c:\users\newta\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\users\newta\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\newta\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Downloading pymysql-1.1.2-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.1.2

# Code for MySQL

In [40]:
from sqlalchemy import create_engine

# Step 1: Connect to MySQL
# Use the details you found in MySQL Workbench
username = "root"          # Default for Workbench
password = "root" # The password you set for MySQL
host = "127.0.0.1"         # Running on your PC
port = "3306"              # Default MySQL port (unlike Postgres' 5432)
database = "python_chemy" # Make sure this database exists in Workbench!

# Note the change: 'mysql+pymysql' instead of 'postgresql+psycopg2'
engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

# Step 2: Load DataFrame into MySQL
table_name = "customer"   
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into MySQL table '{table_name}'!")

Data successfully loaded into MySQL table 'customer'!

In [42]:
# Read back sample (SQL Server uses TOP instead of LIMIT)
pd.read_sql("SELECT  * FROM customer;", engine)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle-aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle-aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle-aged,365
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,32,Venmo,Weekly,Adult,7
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,41,Bank Transfer,Bi-Weekly,Middle-aged,14
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,24,Venmo,Quarterly,Middle-aged,90
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,24,Venmo,Weekly,Adult,7
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,33,Venmo,Quarterly,Middle-aged,90

# Business Questions

#### What is the total revenue generated by male vs. female customers?

In [44]:
pd.read_sql("select gender, SUM(purchase_amount) as revenue from customer group by gender;", engine)

   gender   revenue
0    Male  157890.0
1  Female   75191.0

#### Which customers used a discount but still spent more than the average purchase amount?

In [45]:
sql = """select customer_id, purchase_amount 
        from customer 
        where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer);"""

pd.read_sql(sql, engine)

     customer_id  purchase_amount
0              2               64
1              3               73
2              4               90
3              7               85
4              9               97
..           ...              ...
834         1667               64
835         1671               73
836         1673               73
837         1674               62
838         1676               90

[839 rows x 2 columns]

#### Which are the top 5 products with the highest average review rating?

In [48]:
sql = """
select item_purchased, avg(review_rating) as Average_Product_Rating
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5
"""

pd.read_sql(sql, engine)

  item_purchased  Average_Product_Rating
0         Gloves                3.861429
1        Sandals                3.844375
2          Boots                3.818750
3            Hat                3.801299
4          Skirt                3.784810

#### Compare the average Purchase Amounts between Standard and Express Shipping.

In [49]:
sql = """
select shipping_type, 
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;
"""

pd.read_sql(sql, engine)

  shipping_type  ROUND(AVG(purchase_amount),2)
0       Express                          60.48
1      Standard                          58.46

#### Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

In [51]:
sql = """
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
"""
pd.read_sql(sql, engine)

  subscription_status  total_customers  avg_spend  total_revenue
0                 Yes             1053      59.49        62645.0
1                  No             2847      59.87       170436.0

#### Which 5 products have the highest percentage of purchases with discounts applied?

In [52]:
sql = """
SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;
"""

pd.read_sql(sql, engine)

  item_purchased  discount_rate
0            Hat          50.00
1       Sneakers          49.66
2           Coat          49.07
3        Sweater          48.17
4          Pants          47.37

In [54]:
sql = """WITH customer_type AS (
    SELECT 
        customer_id, 
        previous_purchases,
        CASE 
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
)
SELECT 
    customer_segment, 
    COUNT(*) AS "Number of Customers" 
FROM customer_type 
GROUP BY customer_segment;"""

pd.read_sql(sql, engine)

  customer_segment  Number of Customers
0            Loyal                 3116
1        Returning                  701
2              New                   83

#### Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

In [55]:
sql = """SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;"""

In [56]:
pd.read_sql(sql, engine)

  subscription_status  repeat_buyers
0                 Yes            958
1                  No           2518

#### What is the revenue contribution of each age group?

In [58]:
sql = """
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;
"""

pd.read_sql(sql, engine)

     age_group  total_revenue
0  Young Adult        62143.0
1  Middle-aged        59197.0
2        Adult        55978.0
3       Senior        55763.0

VIDEO LINK : https://www.youtube.com/watch?v=5PrZvPeUw60